#import "JVFloatLabeledTextField.h"
#import "JVFloatLabeledTextView.h"
#import "VPImageCropperViewController.h"
#import "LDXScore.h"
#import "AKSegmentedControl.h"
#import "IGLDropDownMenu.h"
#import "XKeyBoard.h"
#import "ProgressHUD.h"
#import "MJRefresh.h"
#import "UIImageView+WebCache.h"
#import "HZPhotoBrowser.h"
//#import <ShareSDK/ShareSDK.h>
//#import "WXApi.h"
//#import <TencentOpenAPI/QQApiInterface.h>
//#import <ShareSDKConnector/ShareSDKConnector.h>
//#import <ShareSDKUI/ShareSDK+SSUI.h>
//#import <ShareSDKUI/SSUIShareActionSheetStyle.h>
#import "InputView.h"
#import "SWTableViewCell.h"
#import <AVOSCloud/AVOSCloud.h>
